### ISSUE TITLE
Windows build ships without Python bindings

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/gtsam-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See upstream issue: https://github.com/borglab/gtsam/issues/1261

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by sadsimulation** [comment]
Has there been any progress on this?
I can confirm that this is still an issue with Python 3.10 and gtsam 4.2.0 on Win10.

**Comment by Tobias-Fischer** [comment]
Unfortunately no progress. I am not a Windows user myself, so to be honest this is not too high on my priority list.

If you are happy to contribute, you could open a pull request and change https://github.com/conda-forge/gtsam-feedstock/blob/a8b2e3d67a8f3ec1cdc3a9e27510864db651eef2/recipe/bld.bat#L12 to `ON`. Then we could see which issues arise, and I'd be happy to guide you toward resolving them.

**Comment by Tobias-Fischer** [comment]
Fixed in #19
